GET http://localhost:5000/users

###

POST http://localhost:5000/add-user
Content-Type: application/json

{
  "name": "bjir",
  "email": "tes@tes.com",
  "gender": "tes lagi"
}

###

PUT http://localhost:5000/edit-user/1
Content-Type: application/json

{
  "name": "tes",
  "email": "tes@tes.com",
  "gender": "tes lagi"
}

###
DELETE http://localhost:5000/delete-user/2